### PR TITLE
Add support for t-watch-2020 v3

### PR DESCRIPTION
**Pull request by devnoname120**
See https://github.com/jeffmer/TTGO-T-watch-2020-Micropython-OS/issues/1#issuecomment-1556394453

Note that the TTY-USB bridge of my t-watch-2020 v3 unfortunately burned so I couldn't test my changes. :(

The PR is in draft for this reason and the fact that I would like to refactor the changes a bit once we validate that they work.

Pineouts:
- https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/master/docs/watch_2020_v1.md
- https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/master/docs/watch_2020_v2.md
- https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/master/docs/watch_2020_v3.md

### CODE REVIEW

**Comment by jeffmer** [comment]
Unfortunately, I don’t have a V3 watch so cannot test this. Happy to include it if someone with a V3 can see if it all works.

**Comment by thiswillbeyourgithub** [comment]
Congrats @devnoname120  everything seems to be working fine.

**Review by jeffmer — APPROVED** [review]
This looks great - many thanks for submitting this.

**Comment by thiswillbeyourgithub** [comment]
Wasn't expecting a merge that quickly! Expect higher quality code in the future :)!

**Pull request merged**
